logging:
  level:
    com.etna.myapi: DEBUG
    #    org.hibernate.SQL: DEBUG
    #    org.hibernate.type: INFO
    #    org.springframework.integration: INFO
    #    org.springframework.cloud: DEBUG
    #    org.springframework.cloud.openfeign: DEBUG
    #    org.springframework.cloud.netflix.eureka: DEBUG
    #    com.netflix.discovery: DEBUG
    #    com.netflix.eureka: DEBUG

rabbitmq:
  exchange:
    name: "myapi-exchange"
  queue:
    name: "myapi-queue"
  routing:
    key: "java_routing_key"

server:
  port:
    8080

spring:
  application:
    name: ${APPLICATION_NAME:MyAPI}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: redsnoww
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mydb
    password: Leasacha2
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      #use-new-id-generator-mappings: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB