version: "3.7"

services:
  myapi:
    container_name: myapi-spring
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    environment:
      APPLICATION_NAME: MyApi
      MYSQL_HOST: mysql
    volumes:
      - shared-public-volume:/public
    depends_on:
      - rabbitmq
      - mysql

  search:
    container_name: search-dev
    image: redsnoww/search:0.0.1
    ports:
      - "8085:8085"
    depends_on:
      - rabbitmq
      - mysql
      - myapi

  solr:
    image: solr:latest
    ports:
      - "8983:8983"
    volumes:
      - ./solrdata:/var/solr
    command:
      - solr-precreate
      - mycore

  mail-dev-api:
    container_name: mail-dev-api
    image: redsnoww/mail-dev:0.0.1
    depends_on:
      - rabbitmq
      - maildev

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  maildev:
    container_name: maildev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:25"

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Leasacha2
      MYSQL_DATABASE: mydb
      MYSQL_USER: redsnoww
      MYSQL_PASSWORD: Leasacha2
      MYSQL_HOST: mysql
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  shared-public-volume:

networks:
  backend:
  frontend: